services:
  - type: worker
    name: amazon-job-bot-worker
    env: python
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: python main.py
    plan: free
